id: I90035344
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:55:01+00:00'
last_modified: '2022-06-07T18:24:53.721666+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22240
  title: བླ་ན་མེད་པའི་རིན་པོ་ཆེ་གསུམ་གྱི་གཏམ་གྱི་སྦྱོར་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    F011:
      image_group_id: I1KG22313
      title: ''
      total_pages: 170
      order: 1
      base_file: F011.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
